import type { Product } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "md-1800",
    slug: "md-1800-dik-sutluk",
    sku: "CLR-MD-1800-P",
    name: "Cam kapılı sütlük",
    model: "MD-1800",
    family: "reyon",
    division: "ticari",
    short: "Cam kapılı süt ve yoğurt dolabı. Market reyonu için.",
    description:
      "Market reyonları için Market için cam kapılı sütlük. Süt ve yoğurt ürünlerini soğuk tutar; ölçü ve modeli ihtiyaca göre birlikte belirleriz.",
    tempRegime: "pozitif",
    tempRange: "+2 / +8 °C",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R290",
    capacityKw: 3.8,
    capacityBtu: 12970,
    soundDb: 48,
    cop: 3.4,
    voltage: "230V / 50Hz",
    dimensions: { w: 1875, d: 850, h: 2050 },
    weightKg: 312,
    ambientMax: 40,
    glass: "Low-e temperli, ısıtmalı kapı",
    insulation: "60 mm PU, 42 kg/m³",
    highlights: ["Çift hava perdesi", "LED vitrin 4000K", "Gece perdesi", "HACCP alarm"],
    placeholder: {
      file: "COMMERCIAL_MULTIDECK_MILK_CASE.WEBP",
      subtitle:
        "Cam kapılı sütlük dolabı görseli.",
      ratio: "4:5",
    },
  },
  {
    id: "md-2500",
    slug: "md-2500-sarkuteri",
    sku: "CLR-MD-2500-R",
    name: "Şarküteri reyonu",
    model: "MD-2500",
    family: "reyon",
    division: "ticari",
    short: "Açık ön şarküteri reyonu. Peynir, şarküteri ve hazır gıda için.",
    description:
      "Süpermarket şarküteri ve hazır gıda hattı için dıştan motorlu multideck. Çift laminer perde, paslanmaz taban ızgarası ve merkezi sisteme bağlanabilir evaporatör bloğu.",
    tempRegime: "pozitif",
    tempRange: "+2 / +6 °C",
    motor: "remote",
    compressor: "scroll",
    refrigerant: "R448A",
    capacityKw: 5.6,
    capacityBtu: 19110,
    soundDb: 42,
    cop: 3.1,
    voltage: "400V / 50Hz",
    dimensions: { w: 2500, d: 920, h: 2100 },
    weightKg: 268,
    ambientMax: 35,
    glass: "Açık ön + gece perdesi",
    insulation: "70 mm PU, 42 kg/m³",
    highlights: ["Remote evaporatör", "Merkezi bağlantı opsiyonu", "AISI 304 taban", "Elektronik EEV"],
    placeholder: {
      file: "COMMERCIAL_DELI_MULTIDECK_OPEN.WEBP",
      subtitle:
        "Açık ön şarküteri reyonu görseli.",
      ratio: "4:5",
    },
  },
  {
    id: "md-2100x",
    slug: "md-2100x-sutluk-remote",
    sku: "CLR-MD-2100X-R",
    name: "Cam kapılı sütlük (dış motor)",
    model: "MD-2100X",
    family: "reyon",
    division: "ticari",
    short: "Cam kapılı sütlük, motoru dışarıda. Zincir market için.",
    description:
      "Zincir market soğuk reyonları için remote cam kapılı sütlük. Motoru dışarıda olan cam kapılı sütlük. Zincir market ve büyük reyonlar için uygundur.",
    tempRegime: "pozitif",
    tempRange: "+1 / +7 °C",
    motor: "remote",
    compressor: "scroll",
    refrigerant: "R744",
    capacityKw: 4.4,
    capacityBtu: 15010,
    soundDb: 39,
    cop: 3.8,
    voltage: "400V / 50Hz",
    dimensions: { w: 2100, d: 880, h: 2080 },
    weightKg: 241,
    ambientMax: 38,
    glass: "Argon dolgulu low-e çift cam",
    insulation: "60 mm PU",
    highlights: ["CO₂ evaporatör", "Inverter EC fan", "Gece enerji modu", "Sızdırmaz kapı contası"],
    placeholder: {
      file: "COMMERCIAL_REMOTE_DAIRY_CABINET.WEBP",
      subtitle:
        "Dış motorlu cam kapılı sütlük görseli.",
      ratio: "4:5",
    },
  },
  {
    id: "bc-680",
    slug: "bc-680-mesrubat",
    sku: "CLR-BC-680-P",
    name: "Tek kapılı meşrubat dolabı",
    model: "BC-680",
    family: "reyon",
    division: "ticari",
    short: "Tek kapılı soğuk içecek dolabı. Market ve istasyon için.",
    description:
      "Akaryakıt istasyonu ve bakkal hattı için yüksek görünürlüklü meşrubat dolabı. Tropikalize kondenser +45 °C ortam, low-e cam ve R290 doğal soğutucu.",
    tempRegime: "pozitif",
    tempRange: "+1 / +10 °C",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R290",
    capacityKw: 1.6,
    capacityBtu: 5460,
    soundDb: 44,
    cop: 3.2,
    voltage: "230V / 50Hz",
    dimensions: { w: 680, d: 710, h: 1980 },
    weightKg: 118,
    ambientMax: 45,
    glass: "Low-e temperli, self-closing",
    insulation: "50 mm PU",
    highlights: ["Tropikal +45 °C", "LED canopy", "Lockable door", "Can-rack ızgara"],
    placeholder: {
      file: "COMMERCIAL_GLASS_BEVERAGE_COOLER.WEBP",
      subtitle:
        "Tek kapılı meşrubat dolabı görseli.",
      ratio: "3:4",
    },
  },
  {
    id: "bc-1200",
    slug: "bc-1200-mesrubat-cift",
    sku: "CLR-BC-1200-P",
    name: "Çift kapılı meşrubat dolabı",
    model: "BC-1200",
    family: "reyon",
    division: "ticari",
    short: "Çift kapılı yüksek hacimli içecek dolabı.",
    description:
      "Hipermarket ve cash & carry için çift kapılı meşrubat dolabı. Invertör scroll, düşük gürültü ve 12 saatlik kapı-açma dayanımı.",
    tempRegime: "pozitif",
    tempRange: "+2 / +8 °C",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R290",
    capacityKw: 2.9,
    capacityBtu: 9900,
    soundDb: 46,
    cop: 3.5,
    voltage: "230V / 50Hz",
    dimensions: { w: 1200, d: 740, h: 2020 },
    weightKg: 186,
    ambientMax: 43,
    glass: "Çift low-e, ısıtmalı çerçeve",
    insulation: "55 mm PU",
    highlights: ["Inverter scroll", "Çift kapı", "Enerji sınıfı A+", "Dijital termostat"],
    placeholder: {
      file: "COMMERCIAL_TWIN_BEVERAGE_COOLER.WEBP",
      subtitle:
        "Çift kapılı meşrubat dolabı görseli.",
      ratio: "4:5",
    },
  },
  {
    id: "if-2100",
    slug: "if-2100-ada-dondurucu",
    sku: "CLR-IF-2100-P",
    name: "Ada derin dondurucu",
    model: "IF-2100",
    family: "reyon",
    division: "ticari",
    short: "Kayar camlı ada dondurucu. Dondurulmuş gıda için.",
    description:
      "Süpermarket dondurulmuş gıda adası. Panoramik kayar cam, süpermarket koridoru için düşük yükseklik ve plug-in bakır-alüminyum evaporatör.",
    tempRegime: "donuk",
    tempRange: "−18 / −25 °C",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R290",
    capacityKw: 2.4,
    capacityBtu: 8190,
    soundDb: 47,
    cop: 2.4,
    voltage: "230V / 50Hz",
    dimensions: { w: 2100, d: 960, h: 920 },
    weightKg: 198,
    ambientMax: 32,
    glass: "Panoramik kayar, anti-fog",
    insulation: "80 mm PU",
    highlights: ["Kayar cam", "Basket sistemi", "Auto-defrost", "Bumper koruma"],
    placeholder: {
      file: "COMMERCIAL_ISLAND_FREEZER_PANORAMIC.WEBP",
      subtitle:
        "Ada derin dondurucu görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "if-1500",
    slug: "if-1500-ada-kombo",
    sku: "CLR-IF-1500-C",
    name: "Ada kombi dondurucu",
    model: "IF-1500C",
    family: "reyon",
    division: "ticari",
    short: "Yarı soğuk, yarı dondurucu ada. İki sıcaklık bir arada.",
    description:
      "Tek gövdede +4 °C süt ürünü ve −22 °C donuk bölme. Merkezi pack bağlantısı, elektronik EEV ve ayrı defrost döngüleri.",
    tempRegime: "donuk",
    tempRange: "+4 / −22 °C",
    motor: "merkezi",
    compressor: "scroll",
    refrigerant: "R449A",
    capacityKw: 3.1,
    capacityBtu: 10580,
    soundDb: 38,
    cop: 2.8,
    voltage: "400V / 50Hz",
    dimensions: { w: 1500, d: 980, h: 940 },
    weightKg: 164,
    ambientMax: 30,
    glass: "Çift bölmeli kayar cam",
    insulation: "90 mm PU",
    highlights: ["Split sıcaklık", "Merkezi pack", "Çift EEV", "HACCP log"],
    placeholder: {
      file: "COMMERCIAL_COMBO_ISLAND_SPLIT.WEBP",
      subtitle:
        "Kombi ada dondurucu görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "cr-mod-100",
    slug: "cr-mod-100-soguk-oda",
    sku: "CLR-CR-MOD-100",
    name: "Modüler soğuk oda",
    model: "CR-MOD-100",
    family: "soguk-oda",
    division: "depolama",
    short: "Hazır panelli soğuk oda. Süt, et ve sebze deposu için.",
    description:
      "Gıda üretim ve lojistik için 100 m³ modüler soğuk oda. 100 mm poliüretan cam-lock paneller, menteşeli endüstriyel kapı ve hijyenik PVC döşeme.",
    tempRegime: "pozitif",
    tempRange: "0 / +4 °C",
    motor: "remote",
    compressor: "scroll",
    refrigerant: "R448A",
    capacityKw: 12.5,
    capacityBtu: 42650,
    soundDb: 58,
    cop: 2.9,
    voltage: "400V / 50Hz",
    dimensions: { w: 6000, d: 5000, h: 3300 },
    weightKg: 1840,
    ambientMax: 45,
    insulation: "100 mm PU cam-lock, 42 kg/m³",
    highlights: ["Cam-lock panel", "Menteşeli soğuk kapı", "PVC hijyen zemin", "LED soğuk oda armatürü"],
    placeholder: {
      file: "INDUSTRIAL_MODULAR_COLD_ROOM.WEBP",
      subtitle:
        "Modüler soğuk oda görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "cr-blast-40",
    slug: "cr-blast-40-sok-tunel",
    sku: "CLR-CR-BLAST-40",
    name: "Şoklama tüneli",
    model: "CR-BLAST-40",
    family: "soguk-oda",
    division: "depolama",
    short: "Hızlı dondurma tüneli. Et ve hamur işi için −40 derece.",
    description:
      "Et ve unlu mamul şoklama için tünel tipi blast freezer. Yüksek statik basınçlı evaporatör, −40 °C çekirdek sıcaklık ve 90 dakikalık çevrim.",
    tempRegime: "soklama",
    tempRange: "−35 / −45 °C",
    motor: "remote",
    compressor: "screw",
    refrigerant: "R404A",
    capacityKw: 48,
    capacityBtu: 163800,
    soundDb: 72,
    cop: 1.8,
    voltage: "400V / 50Hz",
    dimensions: { w: 8200, d: 2800, h: 3100 },
    weightKg: 4120,
    ambientMax: 40,
    insulation: "150 mm PU, 45 kg/m³",
    highlights: ["Blast tünel", "Çekirdek −18 hedef", "Yüksek hava hızı", "PLC çevrim"],
    placeholder: {
      file: "INDUSTRIAL_BLAST_FREEZE_TUNNEL.WEBP",
      subtitle:
        "Şoklama tüneli görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "cr-slide-250",
    slug: "cr-slide-250-donuk-depo",
    sku: "CLR-CR-SL-250",
    name: "Donuk depo",
    model: "CR-SL-250",
    family: "soguk-oda",
    division: "depolama",
    short: "Büyük dondurucu depo. Sürgülü kapılı soğuk oda.",
    description:
      "Soğuk zincir lojistiği için 250 m³ donuk depo. Sürgülü endüstriyel kapı, yerden ısıtmalı eşik ve 120 mm PU panel.",
    tempRegime: "donuk",
    tempRange: "−18 / −25 °C",
    motor: "remote",
    compressor: "semi-hermetic",
    refrigerant: "R449A",
    capacityKw: 22,
    capacityBtu: 75100,
    soundDb: 64,
    cop: 2.2,
    voltage: "400V / 50Hz",
    dimensions: { w: 10000, d: 7000, h: 3600 },
    weightKg: 3560,
    ambientMax: 42,
    insulation: "120 mm PU cam-lock",
    highlights: ["Sürgülü kapı", "Eşik ısıtıcı", "Raf ankrajı", "Sıcaklık kaydı"],
    placeholder: {
      file: "INDUSTRIAL_FROZEN_STORAGE_SLIDING.WEBP",
      subtitle:
        "Donuk depo soğuk oda görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "mb-ceil-35",
    slug: "mb-ceil-35-tavan-monoblok",
    sku: "CLR-MB-C-35",
    name: "Tavan Monoblok",
    model: "MB-C-35",
    family: "monoblok",
    division: "endustriyel",
    short: "Tavana takılan soğutucu. Küçük soğuk odalar için.",
    description:
      "Konya ve Orta Doğu sahası için tropikalize tavan monoblok. Fabrika şarjlı, vakum testli, soğuk odaya hızlı montaj.",
    tempRegime: "pozitif",
    tempRange: "0 / +4 °C",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R448A",
    capacityKw: 8.4,
    capacityBtu: 28660,
    soundDb: 61,
    cop: 2.7,
    voltage: "400V / 50Hz",
    dimensions: { w: 1640, d: 980, h: 720 },
    weightKg: 186,
    ambientMax: 45,
    highlights: ["Plug & cool", "Tropikal +45 °C", "Fabrika şarjı", "Elektrikli defrost"],
    placeholder: {
      file: "INDUSTRIAL_CEILING_MONOBLOCK.WEBP",
      subtitle:
        "Tavan monoblok soğutucu görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "mb-wall-25",
    slug: "mb-wall-25-duvar-monoblok",
    sku: "CLR-MB-W-25",
    name: "Duvar monoblok",
    model: "MB-W-25",
    family: "monoblok",
    division: "endustriyel",
    short: "Duvara takılan soğutucu. Kasap hücresi ve küçük oda için.",
    description:
      "Küçük soğuk odalar ve kasap hücreleri için duvar monoblok. Kolay servis kapağı, tropikal kondenser ve R290 opsiyonu.",
    tempRegime: "pozitif",
    tempRange: "−2 / +6 °C",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R290",
    capacityKw: 4.9,
    capacityBtu: 16720,
    soundDb: 56,
    cop: 3.0,
    voltage: "230V / 50Hz",
    dimensions: { w: 920, d: 780, h: 860 },
    weightKg: 94,
    ambientMax: 45,
    highlights: ["Duvar montaj", "Servis kapağı", "R290 opsiyon", "Dijital kontrol"],
    placeholder: {
      file: "INDUSTRIAL_WALL_MONOBLOCK.WEBP",
      subtitle:
        "Duvar monoblok soğutucu görseli.",
      ratio: "4:5",
    },
  },
  {
    id: "mb-split-18",
    slug: "mb-split-18-tavan-split",
    sku: "CLR-MB-S-18",
    name: "Split tavan ünitesi",
    model: "MB-S-18",
    family: "monoblok",
    division: "endustriyel",
    short: "İç ünite içeride, motor dışarıda. Sessiz dondurucu oda.",
    description:
      "Dış ünite gürültüsünü sahadan uzak tutan split paket. 25 m hat uzunluğu, elektronik EEV ve kış kiti.",
    tempRegime: "donuk",
    tempRange: "−18 / −22 °C",
    motor: "remote",
    compressor: "scroll",
    refrigerant: "R449A",
    capacityKw: 6.2,
    capacityBtu: 21160,
    soundDb: 52,
    cop: 2.3,
    voltage: "400V / 50Hz",
    dimensions: { w: 1480, d: 640, h: 420 },
    weightKg: 78,
    ambientMax: 43,
    highlights: ["25 m hat", "Kış kiti", "EEV", "Dış ünite sessiz"],
    placeholder: {
      file: "INDUSTRIAL_SPLIT_CEILING_EVAP.WEBP",
      subtitle:
        "Split tavan soğutma ünitesi görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "rack-sc-120",
    slug: "rack-sc-120-scroll-pack",
    sku: "CLR-RACK-SC-120",
    name: "Merkezi soğutma grubu",
    model: "RACK-SC-120",
    family: "merkezi",
    division: "endustriyel",
    short: "Marketlerin ortak soğutma makinesi. Birden fazla dolabı besler.",
    description:
      "Süpermarket merkezi soğutma için 4+1 inverter scroll pack. Paralel yağ yönetimi, elektronik kontrol ve R744 transkritik opsiyon.",
    tempRegime: "pozitif",
    tempRange: "−8 / +8 °C",
    motor: "merkezi",
    compressor: "scroll",
    refrigerant: "R744",
    capacityKw: 120,
    capacityBtu: 409500,
    soundDb: 68,
    cop: 3.6,
    voltage: "400V / 50Hz",
    dimensions: { w: 2800, d: 1200, h: 1850 },
    weightKg: 980,
    ambientMax: 46,
    highlights: ["4+1 inverter", "CO₂ platform", "Paralel yağ", "Uzaktan izleme"],
    placeholder: {
      file: "INDUSTRIAL_SCROLL_COMPRESSOR_RACK.WEBP",
      subtitle:
        "Merkezi soğutma grubu görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "rack-sh-250",
    slug: "rack-sh-250-semi-hermetic",
    sku: "CLR-RACK-SH-250",
    name: "Büyük merkezi soğutma grubu",
    model: "RACK-SH-250",
    family: "merkezi",
    division: "endustriyel",
    short: "Fabrika ve büyük soğuk oda için güçlü soğutma grubu.",
    description:
      "Ağır sanayi soğuk zinciri için 3+1 yarı hermetik pack. Kapasite kademeleri, yağ separatörü ve titreşim izolasyonu.",
    tempRegime: "donuk",
    tempRange: "−30 / −10 °C",
    motor: "merkezi",
    compressor: "semi-hermetic",
    refrigerant: "R449A",
    capacityKw: 250,
    capacityBtu: 853000,
    soundDb: 74,
    cop: 2.1,
    voltage: "400V / 50Hz",
    dimensions: { w: 3600, d: 1400, h: 2100 },
    weightKg: 1680,
    ambientMax: 45,
    highlights: ["3+1 kademe", "Yağ separatörü", "Titreşim izolasyonu", "PLC + SCADA"],
    placeholder: {
      file: "INDUSTRIAL_SEMI_HERMETIC_RACK.WEBP",
      subtitle:
        "Büyük merkezi soğutma grubu görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "rack-screw-400",
    slug: "rack-screw-400-vida",
    sku: "CLR-RACK-SW-400",
    name: "Ağır sanayi soğutma grubu",
    model: "RACK-SW-400",
    family: "merkezi",
    division: "endustriyel",
    short: "En büyük soğutma makinesi. Şok tüneli ve büyük depolar için.",
    description:
      "Bölgesel soğuk depo ve şok tünelleri için vida kompresör. Inverter sürücü, ekonomizer ve su soğutmalı kondenser opsiyonu.",
    tempRegime: "soklama",
    tempRange: "−42 / −25 °C",
    motor: "merkezi",
    compressor: "screw",
    refrigerant: "R404A",
    capacityKw: 400,
    capacityBtu: 1365000,
    soundDb: 78,
    cop: 1.9,
    voltage: "400V / 50Hz",
    dimensions: { w: 4200, d: 1800, h: 2300 },
    weightKg: 2840,
    ambientMax: 46,
    highlights: ["Inverter vida", "Ekonomizer", "Su soğutmalı opsiyon", "Sürekli %10–100"],
    placeholder: {
      file: "INDUSTRIAL_SCREW_COMPRESSOR_PLANT.WEBP",
      subtitle:
        "Ağır sanayi soğutma grubu görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "mt-2000",
    slug: "mt-2000-yatay-sut-tanki",
    sku: "CLR-MT-2000",
    name: "Yatay süt tankı",
    model: "MT-2000",
    family: "sut-tanki",
    division: "depolama",
    short: "Çift cidarlı süt soğutma tankı. Çiftlik ve mandıra için.",
    description:
      "Sağımdan gelen sütü hızlı soğutup +4 °C’de bekletmek için yatay tank. Paslanmaz iç gövde, poliüretan yalıtım ve karıştırıcılı soğutma.",
    tempRegime: "pozitif",
    tempRange: "+2 / +4 °C",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R290",
    capacityKw: 4.2,
    capacityBtu: 14330,
    soundDb: 52,
    cop: 3.1,
    voltage: "400V / 50Hz",
    dimensions: { w: 2800, d: 1450, h: 1600 },
    weightKg: 620,
    ambientMax: 40,
    insulation: "60 mm PU, paslanmaz cidar",
    highlights: ["AISI 304 gövde", "Karıştırıcı", "Dijital termostat", "2.000 litre"],
    placeholder: {
      file: "STORAGE_HORIZONTAL_MILK_TANK.WEBP",
      subtitle:
        "Yatay süt soğutma tankı görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "mt-5000",
    slug: "mt-5000-yatay-sut-tanki",
    sku: "CLR-MT-5000",
    name: "Büyük yatay süt tankı",
    model: "MT-5000",
    family: "sut-tanki",
    division: "depolama",
    short: "Büyük hacimli süt tankı. Kooperatif ve mandıra hattı için.",
    description:
      "Günlük yüksek sağım için 5.000 litre yatay süt tankı. Çift cidar, otomatik yıkama opsiyonu ve dışarıdan bakımı kolay soğutma grubu.",
    tempRegime: "pozitif",
    tempRange: "+2 / +4 °C",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R448A",
    capacityKw: 9.6,
    capacityBtu: 32760,
    soundDb: 56,
    cop: 2.9,
    voltage: "400V / 50Hz",
    dimensions: { w: 4200, d: 1850, h: 1950 },
    weightKg: 1180,
    ambientMax: 42,
    insulation: "80 mm PU, paslanmaz cidar",
    highlights: ["5.000 litre", "Yıkama opsiyonu", "Servis kapağı", "Sıcaklık kaydı"],
    placeholder: {
      file: "STORAGE_LARGE_MILK_TANK.WEBP",
      subtitle:
        "Büyük süt soğutma tankı görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "mg-2",
    slug: "mg-2-morg-hucresi",
    sku: "CLR-MG-2",
    name: "İki kapılı morg hücresi",
    model: "MG-2",
    family: "morg",
    division: "depolama",
    short: "İki kapılı morg soğutma ünitesi. Hastane ve defin için.",
    description:
      "Hastane ve defin hizmetleri için iki çekmeceli morg hücresi. Paslanmaz iç gövde, sızdırmaz kapılar ve sabit +2 °C rejim.",
    tempRegime: "pozitif",
    tempRange: "+2 / +5 °C",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R290",
    capacityKw: 2.1,
    capacityBtu: 7170,
    soundDb: 44,
    cop: 3.0,
    voltage: "230V / 50Hz",
    dimensions: { w: 900, d: 2300, h: 1800 },
    weightKg: 310,
    ambientMax: 35,
    insulation: "80 mm PU",
    highlights: ["İki çekmece", "Paslanmaz iç", "Sızdırmaz kapı", "Dijital termostat"],
    placeholder: {
      file: "STORAGE_MORTUARY_TWO_DRAWER.WEBP",
      subtitle:
        "İki kapılı morg hücresi görseli.",
      ratio: "4:5",
    },
  },
  {
    id: "mg-6",
    slug: "mg-6-morg-odasi",
    sku: "CLR-MG-6",
    name: "Altı kapılı morg odası",
    model: "MG-6",
    family: "morg",
    division: "depolama",
    short: "Altı kapılı morg odası. Hastane morg katı için.",
    description:
      "Hastane morg katı için altı kapılı soğuk oda. Uzaktan motor, paslanmaz raylar ve sabit sıcaklık kaydı.",
    tempRegime: "pozitif",
    tempRange: "0 / +4 °C",
    motor: "remote",
    compressor: "scroll",
    refrigerant: "R448A",
    capacityKw: 6.8,
    capacityBtu: 23200,
    soundDb: 48,
    cop: 2.8,
    voltage: "400V / 50Hz",
    dimensions: { w: 2800, d: 2400, h: 2200 },
    weightKg: 980,
    ambientMax: 38,
    insulation: "100 mm PU cam-lock",
    highlights: ["Altı kapı", "Uzak motor", "Paslanmaz ray", "Sıcaklık kaydı"],
    placeholder: {
      file: "STORAGE_MORTUARY_SIX_DOOR.WEBP",
      subtitle:
        "Altı kapılı morg odası görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "ch-air-80",
    slug: "ch-air-80-hava-chiller",
    sku: "CLR-CH-A-80",
    name: "Hava soğutmalı chiller",
    model: "CH-A-80",
    family: "chiller",
    division: "endustriyel",
    short: "Dışarıya konan chiller. Üretim suyu ve klima santrali için.",
    description:
      "Fabrika proses suyu ve klima santrali için hava soğutmalı chiller. Tropikal kondenser, inverter scroll ve dış ortam montajı.",
    tempRegime: "pozitif",
    tempRange: "+7 / +12 °C su",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R290",
    capacityKw: 80,
    capacityBtu: 273000,
    soundDb: 66,
    cop: 3.3,
    voltage: "400V / 50Hz",
    dimensions: { w: 2200, d: 1100, h: 1950 },
    weightKg: 740,
    ambientMax: 45,
    highlights: ["Hava soğutmalı", "Inverter scroll", "Dış ortam", "Tropikal +45 °C"],
    placeholder: {
      file: "INDUSTRIAL_AIR_COOLED_CHILLER.WEBP",
      subtitle:
        "Hava soğutmalı chiller görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "ch-water-160",
    slug: "ch-water-160-su-chiller",
    sku: "CLR-CH-W-160",
    name: "Su soğutmalı chiller",
    model: "CH-W-160",
    family: "chiller",
    division: "endustriyel",
    short: "Makine dairesi chilleri. Büyük üretim hattı için.",
    description:
      "Yüksek kapasiteli üretim hatları için su soğutmalı chiller. Vidalı kompresör, plakalı eşanjör ve kapasite kademeleri.",
    tempRegime: "pozitif",
    tempRange: "+6 / +12 °C su",
    motor: "dahili",
    compressor: "screw",
    refrigerant: "R449A",
    capacityKw: 160,
    capacityBtu: 546000,
    soundDb: 72,
    cop: 4.1,
    voltage: "400V / 50Hz",
    dimensions: { w: 2800, d: 1400, h: 1850 },
    weightKg: 1320,
    ambientMax: 40,
    highlights: ["Su soğutmalı", "Vida kompresör", "Plakalı eşanjör", "Kademeli kapasite"],
    placeholder: {
      file: "INDUSTRIAL_WATER_COOLED_CHILLER.WEBP",
      subtitle:
        "Su soğutmalı chiller görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "ess-std",
    slug: "endustriyel-sogutma-sistemleri",
    sku: "CLR-ESS",
    name: "Endüstriyel soğutma sistemi",
    model: "ESS",
    family: "endustriyel-sistem",
    division: "endustriyel",
    short: "Fabrika ve üretim için soğutma. Uygun sistemi birlikte belirleriz.",
    description:
      "Fabrika, depo ve işletme için endüstriyel soğutma. Yerinde bakıp uygun sistemi birlikte seçer, kurulum ve servisi biz üstleniriz.",
    tempRegime: "pozitif",
    tempRange: "İhtiyaca göre",
    motor: "remote",
    compressor: "scroll",
    refrigerant: "R448A",
    capacityKw: 0,
    capacityBtu: 0,
    soundDb: 0,
    cop: 0,
    voltage: "400V / 50Hz",
    dimensions: { w: 0, d: 0, h: 0 },
    weightKg: 0,
    ambientMax: 45,
    highlights: ["Keşif sonrası teklif", "Kurulum dahil", "7/24 servis"],
    placeholder: {
      file: "INDUSTRIAL_COOLING_SYSTEM.WEBP",
      subtitle: "Endüstriyel soğutma sistemi görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "evap-std",
    slug: "ic-uniteler-evaporator",
    sku: "CLR-EVAP",
    name: "Soğuk oda iç ünitesi",
    model: "EVAP",
    family: "ic-unite",
    division: "endustriyel",
    short: "Soğuk odanın içindeki ünite. Odaya göre seçilir.",
    description:
      "Soğuk oda ve depo içindeki soğutma ünitesi. Boyut ve modeli odaya göre birlikte belirleriz.",
    tempRegime: "pozitif",
    tempRange: "İhtiyaca göre",
    motor: "remote",
    compressor: "scroll",
    refrigerant: "R448A",
    capacityKw: 0,
    capacityBtu: 0,
    soundDb: 0,
    cop: 0,
    voltage: "400V / 50Hz",
    dimensions: { w: 0, d: 0, h: 0 },
    weightKg: 0,
    ambientMax: 45,
    highlights: ["Odaya göre seçilir", "Keşif sonrası teklif", "Montaj dahil"],
    placeholder: {
      file: "INDUSTRIAL_EVAPORATOR_UNIT.WEBP",
      subtitle: "Soğuk oda iç ünitesi görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "cond-std",
    slug: "kondenser-uniteleri",
    sku: "CLR-COND",
    name: "Kondenser ünitesi",
    model: "COND",
    family: "kondenser",
    division: "endustriyel",
    short: "Dışarıdaki soğutma ünitesi. Sisteme göre seçilir.",
    description:
      "Soğuk oda ve merkezi sistemin dış ünitesi. Güç ve modeli ihtiyaca göre birlikte belirleriz.",
    tempRegime: "pozitif",
    tempRange: "İhtiyaca göre",
    motor: "remote",
    compressor: "scroll",
    refrigerant: "R448A",
    capacityKw: 0,
    capacityBtu: 0,
    soundDb: 0,
    cop: 0,
    voltage: "400V / 50Hz",
    dimensions: { w: 0, d: 0, h: 0 },
    weightKg: 0,
    ambientMax: 45,
    highlights: ["Dış ünite", "Keşif sonrası teklif", "Montaj dahil"],
    placeholder: {
      file: "INDUSTRIAL_CONDENSING_UNIT.WEBP",
      subtitle: "Kondenser ünitesi görseli.",
      ratio: "16:9",
    },
  },
  {
    id: "dik-std",
    slug: "dik-dolap",
    sku: "CLR-DIK",
    name: "Dik dolap",
    model: "DIK",
    family: "dik-dolap",
    division: "ticari",
    short: "Cam kapılı dik soğutucu. İçecek, süt ve ambalajlı ürün için.",
    description:
      "Market, bakkal ve istasyon için cam kapılı dik dolap. Ölçü ve modeli ihtiyaca göre birlikte belirleriz.",
    tempRegime: "pozitif",
    tempRange: "+2 / +8 °C",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R290",
    capacityKw: 0,
    capacityBtu: 0,
    soundDb: 0,
    cop: 0,
    voltage: "230V / 50Hz",
    dimensions: { w: 0, d: 0, h: 0 },
    weightKg: 0,
    ambientMax: 40,
    highlights: ["Cam kapı", "Keşif sonrası teklif", "Montaj dahil"],
    placeholder: {
      file: "COMMERCIAL_UPRIGHT_CABINET.WEBP",
      subtitle: "Cam kapılı dik dolap görseli.",
      ratio: "4:5",
    },
  },
  {
    id: "pasta-std",
    slug: "yas-pasta-dolabi",
    sku: "CLR-PASTA",
    name: "Yaş pasta dolabı",
    model: "PASTA",
    family: "yas-pasta",
    division: "ticari",
    short: "Pastane ve kafe için yaş pasta vitrin dolabı.",
    description:
      "Yaş pasta, tatlı ve kremalı ürünler için vitrin dolabı. Ölçü ve modeli ihtiyaca göre birlikte belirleriz.",
    tempRegime: "pozitif",
    tempRange: "+2 / +8 °C",
    motor: "dahili",
    compressor: "scroll",
    refrigerant: "R290",
    capacityKw: 0,
    capacityBtu: 0,
    soundDb: 0,
    cop: 0,
    voltage: "230V / 50Hz",
    dimensions: { w: 0, d: 0, h: 0 },
    weightKg: 0,
    ambientMax: 40,
    highlights: ["Vitrin camı", "Keşif sonrası teklif", "Montaj dahil"],
    placeholder: {
      file: "COMMERCIAL_CAKE_DISPLAY.WEBP",
      subtitle: "Yaş pasta dolabı görseli.",
      ratio: "4:5",
    },
  },
];

export function getProduct(slug: string) {
  return PRODUCTS.find((p) => p.slug === slug);
}

/** Keşif sonrası teklif; katalog teknik satırı göstermez */
export function isQuoteProduct(product: Product): boolean {
  return product.dimensions.w === 0 && product.capacityKw === 0;
}

export function relatedProducts(product: Product, limit = 3) {
  return PRODUCTS.filter((p) => p.id !== product.id && p.family === product.family).slice(0, limit);
}
